<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WCL.Api\WCL.Api.csproj"/>
    <ProjectReference Include="..\WCL.App\WCL.App.csproj"/>
    <ProjectReference Include="..\WCL.Core\WCL.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
  </ItemGroup>

</Project>
