<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WCL.Core\WCL.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Classic.Avalonia.Theme"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
  </ItemGroup>

</Project>
