<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WCL.Core\WCL.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="ShadUI" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\MainView\MainView.axaml.cs">
      <DependentUpon>MainView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Windows\" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Windows\MainWindow\MainWindow.axaml" />
  </ItemGroup>

</Project>
